<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D34DC2QJ" name="Test" tests="5" failures="1" timestamp="31 Jul 2020 00:54:55 GMT" time="38.486" errors="0">
  <testcase name="failed_TC1" time="0.316" classname="com.busyqa.batch16.uitests.testCases.TC01_LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.busyqa.batch16.uitests.testCases.TC01_LoginTest.failed_TC1(TC01_LoginTest.java:175)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- failed_TC1 -->
  <testcase name="loginTest01" time="10.085" classname="com.busyqa.batch16.uitests.testCases.TC01_LoginTest"/>
  <testcase name="loginTest02" time="2.084" classname="com.busyqa.batch16.uitests.testCases.TC01_LoginTest"/>
  <testcase name="loginTest03" time="2.033" classname="com.busyqa.batch16.uitests.testCases.TC01_LoginTest"/>
  <testcase name="loginTest04" time="6.53" classname="com.busyqa.batch16.uitests.testCases.TC01_LoginTest"/>
</testsuite> <!-- Test -->
